### ISSUE TITLE
Schedule instead of straight download 

### ISSUE THREAD

**Issue by skeith** [wlerin/showroom#2]
How do I create schedule instead of straight watching when invoking `python3.5 showroom.py "Member Name"`?

The current showroom.py will say that MemberName is not defined but I modify it by uncommenting two lines (1054-1055). However it goes to watching instead of scheduling. 

What did I do wrong?

**Comment by wlerin** [comment]
Lines 1054-1055 are part of a placeholder function (`simple_watcher`) that doesn't do anything yet. It doesn't get called by main so uncommenting shouldn't change anything, unless you also removed the quotes on lines 1137 and 1144 (in which case explosions are the expected result, not watching).

If you just type `python showroom.py "Member Name"` it should call the `watch` function... or it would if I hadn't broken that part with the new index.

**Comment by skeith** [comment]
Using member name as arguments is failing. It says that the MemberName is not exist. So my work around that works is uncommenting those lines. 

I'll put more detail later with screenshots

**Comment by wlerin** [comment]
It's possible that my local code is out of sync with github, but from what I'm seeing uncommenting those lines shouldn't have any effect. The problem lies on line 1130, where main tries to call `watch` with a `member_index` variable that no longer exists.

Since I'm going to have to rewrite this anyway, let me make sure I understand what you are trying to do. You want the script to just focus on one room, instead of all the rooms, correct? And instead of going into full watch mode, to read the schedule and wait until they're supposed to come on?

**Comment by skeith** [comment]
Yes, I want the watching one room is functional and ...
I would also like to be able to schedule on for a set of names, meybe we can add member index number on the index files as an optional index to call, so instead of `showroom.py "Member Name"` it would able to take `showroom.py --indexnum 1,4,5,12`

Well, I can make a workaround using a custom index file though

**Comment by wlerin** [comment]
Well you can sort of do this already by creating a custom index ("jdex") file that only has the rooms you want in it, and moving or deleting the other jdex files out of the index directory. But it would be nice if you could just type a list of names on the command line and it would only track those rooms.

**Comment by skeith** [comment]
Yes, I just added that as an update to my comment. I was confused at first because the current github code tells it watch default_member.json while the code has jdex files.

**Comment by wlerin** [comment]
Ah. Are you on the main branch?

https://github.com/wlerin/showroom should default to new-index, which is the branch currently in development. (And also the one with broken watch--it should still work in the old main branch.)

**Comment by skeith** [comment]
I am on default branch which is `new-index`

it still has 

```
MAX_DOWNLOADS = 60
MAX_WATCHES = 50
MAX_PRIORITY = 80
LIVE_RATE = 11.0
SCHEDULE_TICKS = 20
END_HOUR = 0
RESUME_HOUR = 5
DEFAULT_INDEX = 'index/default_members.json'
NEW_INDEX_LOC = 'index
```

which make me confused a bit

**Comment by skeith** [comment]
also, the `--help` shows default-members.json

**Comment by wlerin** [comment]
Ah. Right. I guess I should comment that out and fix the help output too. 

Ah. Actually. That index argument does nothing. Hmm.

**Comment by skeith** [comment]
No rush, I should thank you for this awesome work. Hoping to see the new updates

**Comment by wlerin** [comment]
92c18d62d81baf6a11ba187d857b597557642ae7

It probably needs more testing, but that feature should work now.

Also, `--all` is now the default, if you run it without giving any names. (I suppose I should update the README to reflect this...)

**Comment by skeith** [comment]
Awesome, going to pull later.

Now I need to think of how to port / integrate it with my Discord bot

**Comment by wlerin** [comment]
Depending on what your Discord bot does... you could always write [your own announce.py](https://github.com/wlerin/showroom/blob/new-index/showroom.py#L39) to send the announce message to the bot instead of to the command line.

I don't think that receives Schedule information though, only when rooms go live.

**Comment by skeith** [comment]
I want to pass the command from the bot and outputs the result on Discord. I probably better to go with ssh from the bot. I am still learning and sorry for mentioning this here. It's unrelated to the issue

**Comment by wlerin** [comment]
When you get a better idea of what you want to do, you could open a new "issue" and maybe I can add the functionality here (or you can fork it and maybe I'll merge the new features back in, I dunno).

Right now I don't think there's a way to control the script once it starts (either to change things or to get specific information from it), aside from pressing CTRL+C. This is something I've wanted to fix for a long time, but never gotten around to doing it since there hasn't been a pressing need in my use case.

**Comment by skeith** [comment]
If you want, I can send you my Discord server invite and see how the bot works

and I should close this issue as it is fixed with the recent commit

**Comment by wlerin** [comment]
Yah, that would help. Just PM me on Stage48 or something.

**Comment by skeith** [comment]
sent on your profile on Stage48
